### PR TITLE
Add missing `_skipped_value` attribute in Cython stream class

### PR DESCRIPTION
**Pull request by martinmaillard**
Fixes a regression in 1.8.0.

### CODE REVIEW

**Comment by sohaibfarooqi** [comment]
I am seeing the same issue with 1.8.0. The fix you did however didn't solve the problem.

**Comment by martinmaillard** [comment]
May I ask how you tested it?

**Comment by sohaibfarooqi** [comment]
I added the attribute myself. The worker was still giving same exception.

**Comment by martinmaillard** [comment]
Ok, then it might be because the Cython file needs to be recompiled... which I'm not sure how to do 😄 
Maybe try installing Faust directly from my branch with pip?

**Comment by sohaibfarooqi** [comment]
That could be the reason, I will try the your branch! Thanks for the heads up!

**Comment by mdt-kathur** [comment]
as far as I tried. if I start my zookeeper and Kafka on Mac Mojave, and use Faust -L command to start a Faust app, I'll encounter this _skipped_value problem. but if I start Faust app in a docker environment based on linux python 3.7.4 image, there won't be this problem. I guess it's it's a problem in execute(or compile) cython file

**Pull request merged**
