### PR TITLE
Issue 401

### PR DESCRIPTION
**Pull request by andr83**
## Description

Fix for issue #401 - stop offset commit on gaps in the input kafka topic.

### CODE REVIEW

**Comment by joekohlsdorf** [comment]
I played around with this PR and it seems that it introduces a bug when reading the topic from the beginning. The offset 0 always gets skipped.

**Comment by andr83** [comment]
Hi @joekohlsdorf, thank you for reviewing. Can you please provide more details when it happens to reproduce?

**Comment by joekohlsdorf** [comment]
To reproduce:

```
#!/usr/bin/env python
import faust
import time
from concurrent.futures import ThreadPoolExecutor

app = faust.App("skiptest", broker="kafka://kafka:9092")
topic = app.topic("skiptest", value_type=int)


@app.agent(topic)
async def read_topic(stream):
    async for batch in stream.take(1, within=15):
        print("read value from topic: {}".format(batch))


@app.task()
async def produce():
    for value in range(3):
        print("sending value to topic: {}".format(value))
        await read_topic.send(value=value)


if __name__ == "__main__":
    app.main()
```

Output:
```
[2019-08-21 14:59:41,060: WARNING]: sending value to topic: 0 
[2019-08-21 14:59:41,069: WARNING]: sending value to topic: 1 
[2019-08-21 14:59:41,070: WARNING]: sending value to topic: 2 
[2019-08-21 14:59:41,093: WARNING]: read value from topic: [1] 
[2019-08-21 14:59:41,097: WARNING]: read value from topic: [2] 
```

**Comment by andr83** [comment]
@joekohlsdorf can you please check with latest PR commit? I just checked and result as expected:

```
[2019-08-21 18:48:33,747: WARNING]: sending value to topic: 0 
[2019-08-21 18:48:33,749: WARNING]: sending value to topic: 1 
[2019-08-21 18:48:33,751: WARNING]: sending value to topic: 2 
[2019-08-21 18:48:34,098: WARNING]: read value from topic: [0] 
[2019-08-21 18:48:34,100: WARNING]: read value from topic: [1] 
[2019-08-21 18:48:34,101: WARNING]: read value from topic: [2]
```

Also I don't see any place in the code which cause input record skipping.

**Comment by andr83** [comment]
Ok, I found the issue. Fixed.

**Comment by joekohlsdorf** [comment]
Make sure that the topic does not exist before testing it so that the first sent value goes to offset 0. One way to do it is to change the topic name in the example I posted.

**Comment by joekohlsdorf** [comment]
I tested the updated version of the PR and haven't seen any issues so far.

**Comment by ask** [comment]
Thanks! The fix looks good to me, but fairly complex so let's test it out by merging

**Comment by patkivikram** [comment]
The fix is causing the app to go OOM and crash. 
https://github.com/robinhood/faust/issues/453

**Pull request merged**
